<a href="https://colab.research.google.com/github/skoleti123/Python_AI/blob/main/NumpyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install -U numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 24.4 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cupy-cuda12x 12.2.0 requires numpy<1.27,>=1.20, but you have numpy 2.1.3 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.1.3 which is incompatible.
langchain 0.3.4 requires numpy<2,>=1; python_version < "3.12", but you have numpy 2.1.3 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.1.3 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.1.3 which is incompatible.
pytensor 2.25.5 requires numpy<2,>=1.17.

In [2]:
import numpy as np
my_list=[1,2,3]
#get one-dimentional array
np.array(my_list)


array([1, 2, 3])

In [5]:
my_mat=[[36,45,55],[90,85,87],[75,65,45]]
#get two dimentional array
np.array(my_mat)



array([[36, 45, 55],
       [90, 85, 87],
       [75, 65, 45]])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
x = np.arange(-5, 5, 0.1)
y = np.arange(-5, 5, 0.1)
X, Y = np.meshgrid(x, y)
X.shape

(100, 100)

numpy.linspace is a function in the NumPy library that generates a specified number of evenly spaced values between two endpoints. It is useful for creating ranges of values for plotting, simulations, and numerical analyses.

In [15]:
np.linspace(0,5,2)


array([0., 5.])